# Site settings
title: Zoomulus - Get to the cloud fast
email: info@zoomulus.com
description: > # this means to ignore newlines until "baseurl:"
  Zoomulus is an open source project for cloud computing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zoomulus.com" # the base hostname & protocol for your site
twitter_username: mattvryan
github_username:  mattvryan
repository: https://github.com/zoomulus

# Build settings
markdown: kramdown

exclude:
  - README.md
  - CNAME

